image: node:10.19.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - CI=true npm run build
  artifacts:
    paths:
      - build
  only:
    - master
